#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.0.0 using LevelOfTheory(method='b3lyp',basis='631g(d,p)').
"""
autoGenerated=True
entry(
    index = 0,
    label = "CH3 + C2H4 <=> C3H7",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4682.64,'cm^3/(mol*s)'), n=2.72052, Ea=(19.7827,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1000,'K'), comment="""Fitted to 8 data points; dA = *|/ 1.24741, dn = +|- 0.0301781, dEa = +|- 0.130762 kJ/mol"""),
)

