#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.0.0 using LevelOfTheory(method='b3lyp',basis='631g(d,p)').
"""
autoGenerated=True
entry(
    index = 0,
    label = "r_no2 + r_hydroxylamine <=> p_hono + p_nitric_oxide",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(10.0495,'cm^3/(mol*s)'), n=3.08086, Ea=(14.7702,'kJ/mol'), T0=(1,'K'), Tmin=(400,'K'), Tmax=(1200,'K'), comment="""Fitted to 6 data points; dA = *|/ 1.33796, dn = +|- 0.0384536, dEa = +|- 0.212065 kJ/mol"""),
)

